import React from 'react'
import type { Route } from 'next'
import { PHASE_PRODUCTION_BUILD } from 'next/constants'
import Link from 'next/link'
import CyberIcon from '@/components/cyber/CyberIcon'
import NeonPanel from '@/components/cyber/NeonPanel'
import ContributionHeatmap from '@/components/github/ContributionHeatmap'
import GithubInsights from '@/components/github/GithubInsights'
import {
	type GithubPeriod,
	USERNAME,
	getContributions,
	getProfile,
	getRepos,
	getYearTotals,
	githubYears
} from '@/lib/github'
import { describePeriod, foldLanguages, formatDay, isoDay, periodStats } from '@/lib/github-stats'
import { cn } from '@/lib/utils'

const fmt = (n: number) => n.toLocaleString('en-US')

interface TileSpec {
	icon: string
	label: string
	value: string
	/** What the number means, in words — a tile that needs a hover to be understood isn't one. */
	sub?: string
}

const Tile: React.FC<TileSpec> = ({ icon, label, value, sub }) => (
	<NeonPanel className='clip-notch-sm flex flex-col gap-1 p-4'>
		<CyberIcon icon={icon} className='text-cyber-cyan size-4' />
		<span className='font-display neon-text-yellow text-2xl leading-none font-bold'>{value}</span>
		<span className='text-muted-foreground font-mono text-[0.6rem] tracking-widest uppercase'>{label}</span>
		{sub && <span className='text-muted-foreground/80 text-[0.7rem] leading-snug'>{sub}</span>}
	</NeonPanel>
)

/**
 * `/github` when the contributions API fails during `next build`. Without it the page's
 * `<main>` would hold a heading over nothing — a screen that reads as unfinished to a
 * visitor and as empty to a reviewer.
 */
const GithubUnavailable: React.FC = () => (
	<NeonPanel className='mt-8 flex flex-col items-start gap-3 p-6'>
		<span className='text-cyber-magenta font-mono text-xs tracking-[0.3em] uppercase'>// GitHub data unavailable</span>
		<p className='text-muted-foreground max-w-2xl leading-relaxed'>
			GitHub&apos;s contribution data didn&apos;t come back when this page was built, so there is nothing to chart right
			now. The page tries again every hour — check back later, or read the activity straight from the profile.
		</p>
		<a
			href={`https://github.com/${USERNAME}`}
			target='_blank'
			rel='noopener noreferrer'
			className='text-cyber-cyan hover:text-cyber-yellow inline-flex items-center gap-1.5 font-mono text-xs tracking-widest uppercase transition-colors'>
			<CyberIcon icon='simple-icons:github' className='size-4' /> github.com/{USERNAME}
		</a>
	</NeonPanel>
)

/**
 * The period filter — one row above everything it scopes. Each chip is its own
 * prerendered page, so switching years is a static navigation, not a server round trip.
 */
const PeriodFilter: React.FC<{ period: GithubPeriod; thisYear: number }> = ({ period, thisYear }) => (
	<nav aria-label='Period' className='mt-6 flex flex-wrap gap-2'>
		{['last', ...githubYears(thisYear)].map(p => {
			const active = p === period
			return (
				<Link
					key={p}
					href={(p === 'last' ? '/github' : `/github/${p}`) as Route}
					aria-current={active ? 'page' : undefined}
					className={cn(
						'clip-notch-sm border px-3 py-1 font-mono text-xs tracking-widest uppercase transition-colors',
						active ?
							'bg-cyber-yellow border-cyber-yellow text-black'
						:	'border-border text-muted-foreground hover:border-cyber-cyan hover:text-cyber-cyan'
					)}>
					{p === 'last' ? 'Last 12 mo' : p}
				</Link>
			)
		})}
	</nav>
)

/**
 * The stats body of `/github` and `/github/[year]`. Every figure is derived in
 * `lib/github-stats.ts` while the page is prerendered (and again on each ISR
 * revalidation), so a visitor never waits on GitHub: there is no Suspense boundary here,
 * because nothing renders per request. (Home used to carry a short variant; it links here
 * instead, so a GitHub outage can never change the home page.)
 */
const GithubStats = async ({ period = 'last' }: { period?: GithubPeriod }) => {
	const contrib = await getContributions(period)
	if (!contrib) {
		// On an ISR regeneration, throwing keeps the last good page in the cache — Next retries
		// on the next request. Rendering the fallback instead would cache it for the whole
		// revalidate window, which is how `/github` sat on "data unavailable" for a day. Only
		// `next build` has no good page to fall back on, and a third-party blip there must not
		// fail the deploy.
		if (process.env.NEXT_PHASE !== PHASE_PRODUCTION_BUILD)
			throw new Error(`GitHub contributions unavailable for period "${period}"`)
		return <GithubUnavailable />
	}

	// One "now" for the render: prerendered, then regenerated by ISR.
	const now = new Date()
	const today = isoDay(now)
	const thisYear = now.getUTCFullYear()
	const ongoing = period === 'last' || period === String(thisYear)
	const stats = periodStats(contrib.days, contrib.total, today, ongoing)
	const summary = describePeriod(stats, period, today)

	const { longestStreak: ls, busiestDay } = stats
	const tiles: TileSpec[] = [
		{
			icon: 'mdi:source-commit',
			label: period === 'last' ? 'Contributions · 12 mo' : `Contributions · ${period}`,
			value: fmt(stats.total),
			sub: 'commits, PRs, issues and reviews'
		},
		{
			icon: 'mdi:calendar-check',
			label: 'Active days',
			value: fmt(stats.activeDays),
			sub: `${stats.activePct}% of ${fmt(stats.elapsedDays)} days`
		},
		...(stats.currentStreak !== null ?
			[
				{
					icon: 'mdi:fire',
					label: 'Current streak',
					value: `${stats.currentStreak}d`,
					sub: 'days in a row, up to today'
				}
			]
		:	[]),
		{
			icon: 'mdi:trophy-outline',
			label: 'Longest streak',
			value: `${ls.length}d`,
			sub: ls.start && ls.end && ls.length > 1 ? `${formatDay(ls.start)} – ${formatDay(ls.end, true)}` : undefined
		},
		{
			icon: 'mdi:chart-line-variant',
			label: 'Avg / active day',
			value: stats.avgPerActiveDay.toFixed(1),
			sub: 'on days with any activity'
		},
		{
			icon: 'mdi:flash',
			label: 'Busiest day',
			value: busiestDay ? fmt(busiestDay.count) : '—',
			sub: busiestDay ? formatDay(busiestDay.date, true) : undefined
		}
	]

	const summaryLine = (
		<p className='text-muted-foreground mt-6 max-w-3xl text-sm leading-relaxed md:text-base'>{summary}</p>
	)

	// A year with no recorded activity (2021–2023 today) gets one honest line, not a wall
	// of zeros and an empty heatmap. "Years at a glance" below still shows where the work is.
	// Say only what the data says: the calendar already counts private contributions, so a
	// zero is a zero — not "hidden in private repos".
	const activity =
		stats.total === 0 && stats.elapsedDays > 0 ?
			<>
				{summaryLine}
				<NeonPanel className='clip-notch-sm mt-6 p-5'>
					<p className='text-muted-foreground max-w-2xl text-sm leading-relaxed'>
						This GitHub account recorded no contributions this year. The chart below shows every year side by side —
						select one with activity to open it.
					</p>
				</NeonPanel>
			</>
		:	<>
				{summaryLine}

				<div className='mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3'>
					{tiles.map(t => (
						<Tile key={t.label} {...t} />
					))}
				</div>

				<NeonPanel className='clip-notch mt-5 p-5'>
					<ContributionHeatmap contributions={contrib.days} today={today} levels={stats.levels} />
				</NeonPanel>
			</>

	const [profile, repos, yearTotals] = await Promise.all([getProfile(), getRepos(), getYearTotals()])

	return (
		<>
			<PeriodFilter period={period} thisYear={thisYear} />
			{activity}
			<GithubInsights
				data={{
					period,
					stats,
					// Only the years with a page — the account's first year through this one.
					yearTotals: yearTotals?.filter(y => Number(y.year) <= thisYear) ?? null,
					languages: foldLanguages(repos?.languages ?? []),
					topRepos: repos?.top ?? [],
					profile,
					stars: repos?.stars ?? null
				}}
			/>
		</>
	)
}

export default GithubStats
